# SITE SETUP
# Guide: https://wowchemy.com/docs/get-started/
# Documentation: https://wowchemy.com/docs/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each config section after this section is defined by a name in square brackets (e.g. `[search]`).

############################
## Theme
############################

# Choose a theme.
#   Guide to color themes: https://wowchemy.com/docs/customization/#color-themes
#   Browse the latest built-in font sets at https://github.com/wowchemy/wowchemy-hugo-modules/tree/master/wowchemy/themes/
#   Browse user installed themes in `data/themes/`
theme = "Minimal"

# Enable users to switch between day and night mode?
day_night = true

# Override the theme's font set (optional).
#   Guide to font sets: https://wowchemy.com/docs/customization/#fonts
#   Browse the latest built-in font sets at https://github.com/wowchemy/wowchemy-hugo-modules/tree/master/wowchemy/data/fonts
#   Browse user installed font sets in `data/fonts/`
font = "Minimal"

# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size = "L"

############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type = "Organization"

# Local business type (optional)
# If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
local_business_type = "Swimming Pool"

# Organization name (optional)
# Enter an organization or project name. Defaults to the site title from `config.toml`.
org_name = "Technical Grinder"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = "ทีมโป๊กเกอร์"

############################
## Site Features
############################

# Enable source code highlighting? true/false
# Documentation: https://wowchemy.com/docs/writing-markdown-latex/#highlighting-options
highlight = false
# highlight_languages = ["r"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable LaTeX math rendering? true/false
#   If false, you can enable math on a per page basis as needed.
math = false

# Enable diagram rendering? true/false
#   If false, you can enable diagrams on a per page basis as needed.
diagram = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

# Show related content at the bottom of pages?
show_related = {post = true, project = true, publication = true, talk = true}


############################
## Regional Settings
############################

# Date and time format (refer to https://wowchemy.com/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

# Address format (en-us, en-gb, de, fr-fr, zh).
address_format = "th"

############################
## Advanced
############################

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {enable = true, align = "r", show_logo = true, highlight_active_link = false, show_language = false, show_day_night = true, show_search = true}

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Show a copyright license from creativecommons.org in the site footer?
# Page specific copyright licenses are also possible by adding this option to a page's front matter.
copyright_license = {enable = false, allow_derivatives = false, share_alike = true, allow_commercial = false, notice = "This work is licensed under {license}"}

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js  = []

# Avatars.
# An avatar is an image that appears next to a user's name.
# An avatar can be uploaded as an image named `avatar` to each user's profile or fetched from Gravatar.com.
[avatar]
  # Get user avatars from Gravatar.com? (true/false)
  gravatar = false

  # Choose a shape for avatar images. Options: circle, square.
  shape = "circle"

############################
## Comments
############################
[comments]
  # Comment provider:
  #   "": Disabled
  #   "disqus": Disqus (https://disqus.com)
  #   "commento": Commento (https://commento.io)
  provider = ""

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true, project = true, publication = true, talk = true}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)

  # Configuration of Commento.
  [comments.commento]
    # If self-hosting Commento, enter its URL here (e.g. "https://commento.?.com"), otherwise leave empty.
    url = ""

############################
## Search
############################
[search]
  # Search provider:
  #   "": No search engine
  #   "wowchemy": Built-in search engine
  #   "algolia": Algolia (https://www.algolia.com)
  provider = "wowchemy"

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = true

############################
## Marketing
############################
[marketing]
  google_analytics = ""
  google_tag_manager = ""
  google_site_verification = ""

############################
## Content Management System
############################
[cms]
  branch = "main"
  local_backend = false

############################
## Icon Pack Extensions
############################
[icon.pack]
  ai = true  # Academicons icon pack https://jpswalsh.github.io/academicons/
